name: pathprox
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pytorch=1.10.1
  - torchvision=0.11.2
  - pip=22.1.2
  - numpy=1.23.1
  - protobuf=3.16.0
  - tqdm=4.64.0
  - pip:
    - wandb==0.12.10
