
# system related
cuda: True
gpu: ??
logger_name: ??
seed: 4242

# data related
data_path: data/
batch_size: 200
which_dataset: MNIST_subset

# optimizer
optimizer: SGD
lr: 0.01
momentum: 0.

# model related
arch: mlp_factorized
num_hidden: 400

# training related
total_iter: 100000  # 1000
log_freq: 1000
save_freq: 10000  # 500
